### PR TITLE
Standardize Key Casing to CamelCase

### LINKED ISSUE #133: Connectivity: Keys do not follow same casing as rest of schema
https://github.com/Property-Data-Trust-Framework/schemas/blob/0e663399cd6800a609073b5ad0c68615b893c38c/src/schemas/v2/pdtf-transaction.json#L767

The existing PDFT implementation duplicates keys from the Ofcom payload, as indicated in the documentation: https://api.ofcom.org.uk/api-details#api=ofcom-connected-nations-api&operation=CoverageByPostCodeGet

I suggest a modification where we serialize these keys into camelCase to harmonize with the overall schema. This adjustment facilitates a consistent serialization approach for all objects within the PDFT transaction.

Considering that organizations utilizing PDTF may encounter claims from diverse sources employing keys with varying casings, adopting a uniform approach will alleviate technical challenges and enhance interoperability.

### PR DESCRIPTION
**Pull request by jacknely**
## What:
Transform all keys to camelCase. This change streamlines the PDTF URI structure, offering enhanced consistency, interoperability, and independence from provider-specific case implementations.

## Why:
- **Interoperability**: Enhance compatibility for consuming organizations, enabling seamless serialization of schema data in a uniform manner.
- **Standardization**: Ensure consistent casing across all PDTF URIs, promoting clarity and ease of use:
Before: 
`/propertyPack/titlesToBeSold/0/registerExtract/OCSummaryData/RestrictionDetails/RestrictionEntry/ChargeRestriction/EntryDetails/EntryText`
After: 
`/propertyPack/titlesToBeSold/0/registerExtract/ocSummaryData/restrictionDetails/restrictionEntry/chargeRestriction/entryDetails/entryText`
- **Decoupled Design**: Remove the dependency of the schema on providers' case implementation. All PDTF claims must now adhere to the convention of serializing keys in camelCase.

Resolves #133

To Do:
Update documentation and provide guidance to reflect the new camelCase key convention. Ensure users are informed about the standardized approach for improved integration.

### CODE REVIEW

**Review by edmolyneux — COMMENTED** [review]
Did you miss some of the properties in the `localSearches/localLandCharges` section?

**Comment by jacknely** [comment]
> Did you miss some of the properties in the `localSearches/localLandCharges` section?

Yer, good spot, I've updated now.

**Comment by edmolyneux** [comment]
@jacknely do you mind if we leave this unmerged for a little longer - we're going to have to revise our HMLR collectors...?

**Comment by jacknely** [comment]
> @jacknely do you mind if we leave this unmerged for a little longer - we're going to have to revise our HMLR collectors...?

@edmolyneux no problem. Are we still planning on releasing with v3?

**Comment by amolpednekar** [comment]
@edmolyneux - I remember raising this point with your on a meeting; but you had shared some reasoning for keeping it this way, specifically for the HMLR register fields

**Comment by jacknely** [comment]
closed and re-based from next in #144

**Pull request closed without merging**
