### PR TITLE
Major revamp of representation of search results

### PR DESCRIPTION
**Pull request by edmolyneux**

### CODE REVIEW

**Comment by vivek656** [comment]
In localSearches json keys are in SentenceCase in place of camelCase

**Comment by amolpednekar** [comment]
Other that moving sub-schemas from searches to material facts, have you also added new sub schemas? (E.g. around localSearches)?

**Comment by edmolyneux** [comment]
> In localSearches json keys are in SentenceCase in place of camelCase

We've elected to match the case of the actual JSON responses from HMLR in this case, see this example as supplied to us below: 

`<soap:Envelope xmlns:soap="http://schemas.xmlsoap.org/soap/envelope/">
    <soap:Body>
        <ns5:performSearchResponse xmlns:ns2="http://www.oscre.org/ns/eReg/MR01-20090605/PollRequest"
            xmlns:ns3="http://www.landregistry.gov.uk/LLC/LLCSearchResponseV2_0"
            xmlns:ns4="http://www.landregistry.gov.uk/LLC/LLCSearchRequestV2_0"
            xmlns:ns5="http://llcsearchv2_0.ws.bg.lr.gov/">
            <return>
                <ns3:GatewayResponse>
                    <ns3:TypeCode>30</ns3:TypeCode>
                    <ns3:Results>
                        <ns3:ExternalReference>ABC</ns3:ExternalReference>
                        <ns3:ActualPrice>
                            <ns3:GrossPriceAmount>1500</ns3:GrossPriceAmount>
                        </ns3:ActualPrice>
                        <ns3:SearchArea ns3:format="JSON"><![CDATA[{"type":"FeatureCollection","features":[{"type":"Feature","geometry":{"type":"Polygon","coordinates":[[[292403.1591430201,92980.43954658421],[292407.18414302013,92984.2895465842],[292424.1591430201,92967.31454658421],[292419.9591430201,92963.9895465842],[292403.1591430201,92980.43954658421] ] ]},"properties":{"id":1.573722712692E12}}]}]]></ns3:SearchArea>
                        <ns3:SearchDateTime>2019-11-19T16:48:48.000Z</ns3:SearchDateTime>
                        <ns3:SearchDescription>24 Sidwell St</ns3:SearchDescription>
                        <ns3:NumberSearchesFound>9</ns3:NumberSearchesFound>
                        <ns3:ChargesAlternateFormat ns3:format="JSON"><![CDATA[[{"Category":"Planning","ChargeSubCategory":"Planning agreement","Location":{"line1":"24 Sidwell Street","line2":"Exeter","Postcode":"EX4 6NN"},"Description":"Additional text for charge description","Law":"Town and Country Planning Act 1990 section 106","LegalDocument":"Agreement","OriginatingAuthority":"HM Land Registry","AuthorityReference":"AuthRef-13579","SourceOfInformation":"Further information is available in planning department","RegistrationDate":"14 Nov 2019","CreationDate":"20 Feb 2019","HMLRReference":"LLC-10TW","Adjoining":false,"ChargeExtent":{"type":"FeatureCollection","features":[{"type":"Feature","geometry":{"type":"Polygon","coordinates":[[[292403.28359375,92980.3875],[292407.13359374995,92984.15],[292424.02109374997,92967.0875],[292419.99609375,92963.5875],[292403.28359375,92980.3875] ] ]},"properties":{"id":1573721596859}}]}},{"Category":"Financial","Location":{"line1":"24 Sidwell Street","line2":"Exeter","Postcode":"EX4 6NN"},"Law":"Local Land Charges Act 1975 section 6(2)","LegalDocument":"Deed","OriginatingAuthority":"HM Land Registry","AuthorityReference":"AuthRef-finance1","SourceOfInformation":"Further information about this financial charge","RegistrationDate":"14 Nov 2019","CreationDate":"14 Oct 2019","Amount":"5000.00","InterestRate":"4%","HMLRReference":"LLC-10TX","Adjoining":false,"ChargeExtent":{"type":"FeatureCollection","features":[{"type":"Feature","geometry":{"type":"Polygon","coordinates":[[[292403.19609374995,92980.56249999999],[292419.99609375,92963.93749999999],[292424.10859375,92967.34999999999],[292406.95859374997,92984.23749999999],[292403.19609374995,92980.56249999999] ]]},"properties":{"id":1573721894086}}]}},{"Category":"Land compensation","Location":{"line1":"24 Sidwell Street","line2":"Exeter","Postcode":"EX4 6NN"},"Description":"Land Compensation Charge description - optional","Law":"Land Compensation Act 1973 section 52(8)","LegalDocument":"Order","OriginatingAuthority":"HM Land Registry","AuthorityReference":"LandCompRef-123","SourceOfInformation":"Further information about this Land Compensation charge","RegistrationDate":"14 Nov 2019","InterestInLand":"Freehold","AdvancePayment":"3500.00","TotalCompensation":"4500.00","AgreedOrEstimated":"Agreed amount","HMLRReference":"LLC-10TY","Adjoining":false,"ChargeExtent":{"type":"FeatureCollection","features":[{"type":"Feature","geometry":{"type":"Polygon","coordinates":[[[292403.19609374995,92980.47499999999],[292420.08359374997,92964.025],[292424.19609374995,92967.61249999999],[292406.87109375,92984.15],[292403.19609374995,92980.47499999999] ] ]},"properties":{"id":1573722067420}}]}},{"Category":"Financial","Location":{"line1":"24 Sidwell Street","line2":"Exeter","Postcode":"EX4 6NN"},"Description":"Charge description - Financial charge with no amount stated","Law":"Planning (Listed Buildings and Conservation Areas) Act 1990 section 55(5D)","LegalDocument":"Undertaking","OriginatingAuthority":"HM Land Registry","AuthorityReference":"FinancialRef-2","SourceOfInformation":"Further information - Financial charge no amount provided","RegistrationDate":"14 Nov 2019","CreationDate":"01 Jan 2019","HMLRReference":"LLC-10TZ","Adjoining":false,"ChargeExtent":{"type":"FeatureCollection","features":[{"type":"Feature","geometry":{"type":"Polygon","coordinates":[[[292403.28359375,92980.47499999999],[292407.04609375,92984.23749999999],[292424.02109374997,92967.2625],[292420.17109375,92963.7625],[292403.28359375,92980.47499999999] ] ]},"properties":{"id":1573722232467}}]}},{"Category":"Light obstruction notice","LocationDominantBuilding":{"line1":"24 Sidwell Street","line2":"Exeter","Postcode":"EX4 6NN"},"Law":"Rights of Light Act 1959 section 2(4)","LegalDocument":"Certificate","SourceOfInformation":"https://help.landregistry.gov.uk/app/contactus_LLC","RegistrationDate":"14 Nov 2019", "Applicants":[{"Applicant":{"ApplicantName":"Cyril Holmes","ApplicantAddress":{"line1":"77 Victoria Street","line2":"Exeter","Postcode":"EX4 6JG","Country":"United Kingdom"}}},{"Applicant":{"ApplicantName":"Stanley Holmes","ApplicantAddress":{"line1":"88 Victoria Street","line2":"Exeter","Postcode":"EX4 6JG","Country":"United Kingdom"}}}],"HeightServientLandDevelopment":"85 feet","CoversAllOrPartOfExtent":"All of the extent","InterestInLand":"Freehold owner","AvailableDocuments":[{"Document":"Definitive certificate","StartDate":"01 Oct 2019","EndDate":"14 Nov 2040"},{"Document":"Form A and colour plan"}],"HMLRReference":"LLC-10V0","Adjoining":false,"ChargeExtent":{"type":"FeatureCollection","features":[{"type":"Feature","geometry":{"type":"Polygon","coordinates":[[[292403.34375000006,92980.559765625],[292420.23125,92963.759765625],[292423.99375,92967.259765625],[292406.75625000003,92984.14726562501],[292403.34375000006,92980.559765625] ] ]},"properties":{"id":1573722453082}}]}},{"Category":"Planning","ChargeSubCategory":"Conditional planning consent","Location":"moo","Law":"Town and Country Planning Act 1990 section 70","LegalDocument":"Planning permission","OriginatingAuthority":"Blackpool Borough Council","AuthorityReference":"far","SourceOfInformation":"sasas","RegistrationDate":"21 Aug 2019","HMLRReference":"LLC-2Z","Adjoining":false,"ChargeExtent":{"type":"FeatureCollection","features":[{"type":"Feature","geometry":{"type":"Polygon","coordinates":[[[290956.58938527975,93699.44022241171],[292633.44809024624,94774.1706257097],[294237.03701786726,93644.30732313858],[294237.03701786726,92091.75845947347],[292724.6139906455,91803.33394711885],[290956.58938527975,93699.44022241171] ] ]},"properties":{"id":1566406338082}}]}},{"Category":"Planning","ChargeSubCategory":"Conditional planning consent","Location":"Totally normal description nothing to see here.\r\n","Law":"Town and Country Planning Act 1990 section 70","LegalDocument":"Planning permission","OriginatingAuthority":"HM Land Registry","SourceOfInformation":"Totally normal location to find information regarding this charge nothing to see here","RegistrationDate":"29 Jul 2019","HMLRReference":"LLC-2D","Adjoining":false,"ChargeExtent":{"type":"FeatureCollection","features":[{"type":"Feature","geometry":{"type":"Polygon","coordinates":[[[295491.1448869982,94332.90102284876],[293665.54454520135,94500.90102284876],[291246.3447160998,94108.90102284876],[290383.94505789666,92652.90102284876],[290910.3447160998,91107.30110829798],[292388.7452287951,89908.90102284876],[293508.7452287951,90323.30068105189],[295972.7452287951,90849.7007665011],[295647.94505789666,93156.90102284876],[295491.1448869982,94332.90102284876] ] ]},"properties":{"id":1564414377311}}]}},{"Category":"Planning","ChargeSubCategory":"Conditional planning consent","Location":"land to the north of the bypass\u0027 or \u002720-26 High Street","Description":"AaAa","Law":"Town and Country Planning Act 1990 section 70","LegalDocument":"Planning permission","OriginatingAuthority":"HM Land Registry","SourceOfInformation":"l","RegistrationDate":"05 Jul 2019","HMLRReference":"LLC-23","Adjoining":false,"ChargeExtent":{"type":"FeatureCollection","features":[{"type":"Feature","geometry":{"type":"Polygon","coordinates":[[[293951.5055058867,93871.6719197249],[292275.2072097857,94610.11763983752],[291379.6913726803,92563.71956664168],[293044.039124954,91872.8720876432],[293951.5055058867,93871.6719197249] ] ]},"properties":{"id":1562321721756}}]}},{"Category":"Housing / buildings","ChargeSubCategory":"Grant","Location":"Test location","Description":"UPDATING THIS FOR REPEATING SEARCH FUNKSHUN PLEASE CHANGE I NO LONGER WISH TO WORK ON THIS","Law":"Ancient Monuments Act 1931","LegalDocument":"Licence","OriginatingAuthority":"HM Land Registry","AuthorityReference":"No","SourceOfInformation":"Table 3rd row boi","RegistrationDate":"10 Jun 2019","CreationDate":"18 Nov 2000","HMLRReference":"LLC-1R","Adjoining":false,"ChargeExtent":{"type":"FeatureCollection","features":[{"type":"Feature","geometry":{"type":"Polygon","coordinates":[[[293609.62524639774,93941.42285711598],[290701.97290264774,93785.67285711598],[290703.94165264774,91569.48926336598],[293961.75805889774,91679.41113836598],[293609.62524639774,93941.42285711598] ]]},"properties":{"id":1560172505614}}]}}]]]></ns3:ChargesAlternateFormat>
                        <ns3:SearchReference>000004827</ns3:SearchReference>
                    </ns3:Results>
                </ns3:GatewayResponse>
            </return>
        </ns5:performSearchResponse>
    </soap:Body>
</soap:Envelope>
`

**Comment by edmolyneux** [comment]
> Other that moving sub-schemas from searches to material facts, have you also added new sub schemas? (E.g. around localSearches)?

No, below `localSearches` are just the original LLC1 and CON29R schemas

**Review by amolpednekar — APPROVED** [review]
LGTM

**Pull request merged**
