### PR TITLE
Add full TA7 References

### PR DESCRIPTION
**Pull request by edmolyneux**
(no version bump included in this case, might wrap this up with some of the other reference additions forthcoming?)

### CODE REVIEW

**Comment by amolpednekar** [comment]
I was working on a branch for this, but will abandon it and add review comments here as I see any missing stuff

Using 3rd Edition 2023 as reference: [TA7-Leasehold-Information-Form.pdf](https://github.com/Property-Data-Trust-Framework/schemas/files/11616531/TA7-Leasehold-Information-Form.pdf)

**Comment by amolpednekar** [comment]
* Add mapping for address fields ? (line1,2, town, postcode)
* "ta7Ref": "5.8", is a yesNo question but if yes, requires details
* "ta7Ref": "11.3", the current title is: "Has a Leaseholder Deed of Certificate been served on the Landlord in relation to the property or remedial works required to the property?", which is quite different to the actual ta7 question, "Is there a Leaseholder Deed of Certificate for the property?". Should we resolve this by adding a "ta7Title" key?
* "ta7Ref": "11.1" is missing, can be added on "buildingSafetyRemediation" ? 
  *   "ta7Title": "Have any remediation works on the building been proposed or carried out?",
  * 11.1.0, 11.1.1 can be added under details and attachments respectively

**Comment by amolpednekar** [comment]
For 11.5, title is "Landlord's Certificate." but the ta7Tile and options are different

- "ta7Title": "Has the seller received a Landlord’s Certificate and the accompanying evidence?",
  "ta7enum": [
     "Yes",
     "No"
   ],

  If yes, attached or to follow
  
 For 11.3b, title & options are different
 
  "title": " Please supply a copy of the leaseholder deed of certificate and the accompanying evidence",
"type": "string",
"enum": [
       "Attached",
      "To follow"
  ]

**Comment by edmolyneux** [comment]
- have left 5.8 as-is: No details referenced on TA7

Other properties have been added as proposed above @amolpednekar , and also `extractOverlay.js` updated to support e.g. `ta7Enum` and `ta7Title`, copying each of these into the ta7 overlay just as `ta7Required` would be, as their base `enum`, `title` and `required` properties in the overlay.

**Review by amolpednekar — APPROVED** [review]
LGTM

**Comment by amolpednekar** [comment]
A point raised by @vivek656 

@edmolyneux  - Looking at the below example, the `pdtf-transaction.json`  wont have "Not Applicable", and will fail validation in a non-form context

Feels like the default `enum` field should contain all possible values, and the overlay (Form) specific enums should be a subset of them
image

**Review by amolpednekar — CHANGES_REQUESTED** [review]
Waiting for confirmation on the previous comment

**Comment by edmolyneux** [comment]
Good point. I'll fix

**Review by amolpednekar — APPROVED** [review]
LGTM

**Pull request merged**
