### PR TITLE
Adding Data Points to Schema , related to listing Information

### PR DESCRIPTION
**Pull request by vivek656**
Added some listing information data, that is used by various property information portals, 
Summary of major data points added. 
1. location information, such as Google Street view POV info, British National Grid Coordinates
2. added inside materialFacts, nearby facilities, like schools, transport, healthcare, etc.
3. added inside materialFacts, residentialPropertyFeatures, including number of bedrooms, bathrooms, etc.
4. added inside materialfacts , buildInformation, including total floors, area, etc.
5, contact details for local authority

### CODE REVIEW

**Comment by vivek656** [comment]
data points added do not contain any new reference to the form. 
WILL BE running extractOverlays js function to generate new transaction schema and skeleton json, only after required approval.
PLLZ comment before approving

**Comment by edmolyneux** [comment]
I think it would be useful to have a discussion on this one:

- would be good to understand the thinking behind including for example comprehensive contact details for local healthcare facilities etc and whether this is material property data? Does this come from an existing structure used elsewhere that we're duplicating here?
- worth thinking about district vs council (and new unitary) local authorities and how to model these, if we're going to make changes in that area
- are the residential property features aligned with existing Rightmove ADF formats etc?
- we seem to be duplicating title deed information outside the official register extract structure?
- does the added 'first page of EPC image' field belong in the verification evidence attachment that supports the data that we're storing, rather than as part of the schema?

**Comment by vivek656** [comment]
@edmolyneux , after meeting changed the data points accordingly
1. changed dining to diningAreas (as it sounds more descriptive and clear) in residentialPropertyFeatures
2. in transport in place of 6 fields  of diff objects created transport as an array and added enum type for diff transport services()
remove 
3. contact details from local authority
4. in hospital added containsAccidentAndEmergencyFacility as yesNoNotKnown
5. in healthcare, in opening hours, with days I added the enum for day name, eg Mon, tue etc (img 2)

**Comment by edmolyneux** [comment]
Some tweaks:
- Moved the new sections to join the other general listing information like price, location, connectivity, towards the top of the schema
- Changed titles to sentence case as used in the rest of the schema
- Renamed floor area as internalArea and separated out the value from the units to align with the Rightmove equivalent, removed the updatedDate as this should be from the claim datetime
- Updated the BNG to reflect the more correct description of x- and y-coords as Eastings and Northings
- Removed EPC updateDate, should be the certificate date or the claim date, depending on what this relates to

Not sure about CouncilTaxMonthlyCharge - we have the annual charge already so should this be 'chargeAmount' and 'frequencyUnit' as obviously these are mathematically related?

**Comment by vivek656** [comment]
@edmolyneux , 
its correct monthly charge can be inferred by annual change.
need some more discussion on frequency unit

**Comment by vivek656** [comment]
@edmolyneux can you please tell me the reason for removing the update date?? I think that's a field, that means when the council tax last updated.

**Comment by edmolyneux** [comment]
Does this mean 'with effect from' which might be obtained from the CT website etc? Or is this the date the information was fetched and added to the schema?

If the former, we should have 'withEffectFromDate' as a property.

If the latter, this information in in the verification.

**Comment by vivek656** [comment]
got it @edmolyneux it looks like, it can be inferred from other data points or vouch  , but we still need some changes in council tax, as only annual charge, will not tell every details wrt to charges and cycle of council tax,
right now we good , and can merge this pr.
will create an issue for other needed changes

**Review by edmolyneux — APPROVED** [review]

**Pull request merged**
